version: '3'

services:
  frontend:
    build: ./frontend/.
    environment:
      - NODE_ENV=development
    volumes:
      - ./frontend/:/user/src/app/
    working_dir: /user/src/app/
    ports:
      - '3000:3000'
    tty: true
